"""Materialize the nv_small reference convolution for the two DUTs.

Source: ext/nvdla/verif/tests/trace_tests/nv_small/dc_13x15x64_5x3x64x16_int8_0.
Keep its register order and byte payload; only relocate the three DMA buffers.
"""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent.parent
NAME = "dc_13x15x64_5x3x64x16_int8_0"
SOURCE = ROOT / "ext/nvdla/verif/tests/trace_tests/nv_small" / NAME
FEATURE, WEIGHT, OUTPUT = 0x80010000, 0x80020000, 0x80040000
SIZE = 0x3C00


def payload(path):
    data = bytearray(SIZE)
    pattern = re.compile(r"offset:(0x[0-9a-f]+), size:(\d+), payload:([^}]+)")
    for offset, size, values in pattern.findall(path.read_text()):
        raw = bytes(int(value, 16) for value in values.split())
        assert len(raw) == int(size)
        pos = int(offset, 16)
        data[pos:pos + len(raw)] = raw
    return data


def c_array(name, values):
    lines = [f"__attribute__((section(\".conv_{name}\"), used))",
             f"const unsigned char conv_{name}[0x{len(values):x}] = {{"]
    for index in range(0, len(values), 16):
        lines.append("    " + ", ".join(f"0x{x:02x}" for x in values[index:index + 16]) + ",")
    return "\n".join(lines + ["};", ""])


def main():
    (ROOT / "build").mkdir(exist_ok=True)
    cfg = (SOURCE / f"{NAME}.cfg").read_text()
    regs = {}
    for path in (ROOT / "ext/nvdla/outdir/nv_small/spec/manual").glob("NVDLA_*.h"):
        regs.update((name, int(offset, 16)) for name, offset in re.findall(
            r"^#define (NVDLA_\w+_0)\s+_MK_ADDR_CONST\((0x[0-9a-f]+)\)",
            path.read_text(), re.M))
    entries = []
    for unit, reg, value in re.findall(r"reg_write\((NVDLA_\w+)\.(\w+_0),\s*(0x[0-9a-f]+)\)", cfg):
        name = f"{unit}_{reg}"
        value = int(value, 16)
        value = {0x80000000: FEATURE, 0x80004100: WEIGHT,
                 0x90000000: OUTPUT}.get(value, value)
        entries.append((regs[name], value, name))
    assert len(entries) > 100
    first_enable = next(i for i, (_, _, name) in enumerate(entries)
                        if name == "NVDLA_SDP_D_OP_ENABLE_0")
    assert [name for _, _, name in entries[first_enable:]] == [
        f"NVDLA_{unit}_D_OP_ENABLE_0"
        for unit in ("SDP", "CACC", "CMAC_A", "CMAC_B", "CSC", "CDMA")]
    loose = ROOT / "dut/loose/conv_commands.h"
    loose.write_text("// Generated by tools/gen_conv.py from the nv_small trace.\n"
                     "struct conv_write { unsigned short offset; unsigned value; };\n"
                     f"enum {{ CONV_CONFIG_COUNT = {first_enable}, "
                     f"CONV_COMMAND_COUNT = {len(entries)} }};\n"
                     "static const struct conv_write conv_commands[] = {\n" +
                     "".join(f"    {{0x{addr:04x}, 0x{val:08x}}}, // {name}\n"
                             for addr, val, name in entries) + "};\n")
    tight = ROOT / "dut/tight/conv_commands.svh"
    tight.write_text("// Generated by tools/gen_conv.py from the nv_small trace.\n"
                     f"localparam int CONV_CONFIG_COUNT = {first_enable};\n"
                     f"localparam int CONV_COMMAND_COUNT = {len(entries)};\n"
                     "function automatic csb_command_t conv_command(input logic [7:0] index);\n"
                     "    case (index)\n" +
                     "".join(f"        8'd{i}: conv_command = {{16'h{addr:04x}, 32'h{val:08x}}}; // {name}\n"
                             for i, (addr, val, name) in enumerate(entries)) +
                     "        default: conv_command = '0;\n"
                     "    endcase\nendfunction\n")
    for kind, short in (("feature", "input"), ("wt", "weight")):
        raw = payload(SOURCE / f"{NAME}_in_{kind}.dat")
        (ROOT / f"dut/loose/conv_{short}.h").write_text(c_array(short, raw))
        (ROOT / f"dut/tight/conv_{short}.h").write_text(c_array(short, raw))
        (ROOT / f"build/conv_{short}.bin").write_bytes(raw)
    print(f"Generated {len(entries)} register writes; {first_enable} before enable")


if __name__ == "__main__":
    main()
